name: Feature Request
description: Suggest an idea for this project
title: "[Req]: "
labels: ["enhancement", "triage"]
assignees:
  - njobypet
body:
  - type: markdown
    attributes:
      value: |
        Please complete the following form.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: e.g. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: e.g. I propose that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives you've considered
      description: Walk through your thought process and how you arrived at your solution.
      placeholder: |
        e.g. Some alternative approaches might be:
                1. ...
                2. ...

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.