# This is a basic workflow to help you get started with Actions

name: analyze workloads


# Controls when the workflow will run
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      # Cancel any previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0


      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Rocm
        run: |
          sudo ./cmake/rocm_install.sh
          sudo apt-get update
          sudo apt-get dist-upgrade -y
          sudo apt-get autoclean
      - name: Install python prereqs
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pyinstaller pytest pytest-cov
          
      - name: build and install 
        run: |
          ls
          ls src
          ls src/mibench
          ls src/mibench/roofline
          cmake -B build-omniperf -DCMAKE_INSTALL_PREFIX=/opt/omniperf -DROCM_VERSIONS="4.3.1" "4.5.2" "5.0.2" "5.1.3" "5.2.3"
          cmake --build build-omniperf --target all
          cmake --build build-omniperf --target install
      - name: run ctest
        run: |
          cd build-omniperf
          ctest --verbose -R test_analyze_workloads test_saved_analysis
